/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "vector.h"
#include <cassert>

int main() {
    // Vector::Greeter greeter;
    // assert(greeter.greeting().compare("Hello, World!") == 0);
    // return 0;
}
