/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "vector.h"

using namespace std;
using namespace Vector;

int main () {
    VArray<int> b;
    b.reserve(3);
    b.push_back(3);
    b.push_back(4);
    b.push_back(5);

    for(size_t i = 0; i < 3; ++i) cout << b[i] << endl;

    return 0;
}
